robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 1000

nn_controller:
  nn_layers: [13, 10, 6, 3]
  weight_init: [-10, 10]
  activation_funcs: [sigmoid, sigmoid, softmax]

warehouse:
  box_radius: 5.0
  width: 500
  height: 500
  number_of_agents: 10
  number_of_boxes: 100
  repulsion_wall: 25
  repulsion_object: 5
  object_position: 0

train:
  population_size: 100
  n_generations: 100
  metric: TODO
  mutation_rate: 0.15
  crossover_rate: 0.1
  elitism: 0.15
  parallel: True
  

faults: []

time_limit: 3000
animate: False
save_animation: False
export_data: True
export_steps: 3000
heading_bias: False
box_attraction: False
heading_change_rate: 10 # ticks per change in heading


