robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 1000

nn_controller:
  nn_layers: [18, 15, 6, 3]
  weight_init: [-10, 10]
  activation_funcs: [sigmoid, sigmoid, softmax]

warehouse:
  box_radius: 5.0
  width: 500
  height: 500
  number_of_agents: 20
  number_of_boxes: 200
  repulsion_wall: 25
  repulsion_object: 5
  object_position: 0

train:
  population_size: 300
  n_generations: 300
  metric: right_left
  mutation_rate: 0.25
  crossover_rate: 0.2
  elitism: 0.15
  parallel: True
  #start_from: data/pretrain/1749917428_train_41/population.csv

faults: []

animate: False
save_animation: False
export_data: True
heading_bias: False
box_attraction: True
heading_change_rate: 10 # ticks per change in heading


