robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 100
  nn_layers: [9, 5, 3]
  weight_init: random
  activation_funcs: [sigmoid, softmax]

warehouse:
  box_radius: 5.0
  width: 500
  height: 500
  number_of_agents: 20
  number_of_boxes: 200
  repulsion_wall: 25
  repulsion_object: 5
  object_position: 0

train:
  population_size: 5
  n_generations: 100
  metric: TODO
  mutation_rate: 0.1
  crossover_rate: 0.5
  elitism: 0.1
  

faults: []

time_limit: 2000
animate: False
save_animation: False
export_data: True
export_steps: 2000
heading_bias: False
box_attraction: False
heading_change_rate: 10 # ticks per change in heading


