robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 100

warehouse:
  box_radius: 5.0
  width: 500
  height: 500
  number_of_agents: 10
  number_of_boxes: 20
  repulsion_wall: 25
  repulsion_object: 5
  object_position: 0

faults: []

time_limit: 10000
animate: False
save_animation: False
heading_bias: False
box_attraction: False
heading_change_rate: 10 # ticks per change in heading


